language: java
before_install:
 - cd test-repos
 - unzip \*.zip
 - git clone https://github.com/rails/rails.git
 - cd ..
script: "mvn cobertura:cobertura"
jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

